# Data path. adjust them!
common:
    image_file: "/home/harry/data/HK/0.png"
    pcd_file: "/home/harry/data/HK/0.pcd"
    result_file: "/home/harry/data/HK/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1364.45, 0.0,      958.327,
                0.0,     1366.46,  535.074,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/harry/catkin_ws/ws_livox_camera_calib/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
